from __future__ import annotations

import ast
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SELF = Path(__file__).resolve()

FORBIDDEN = [
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "placeholder",
    "skeleton",
    "todo",
    "comprehensive",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
    "auto-derived",
    "auto-driven",
]

EMOJI = re.compile("[\U0001f000-\U0001faff\U00002600-\U000027bf\U0001f1e6-\U0001f1ff]")


def _python_files() -> list[Path]:
    return sorted((ROOT / "graticule").glob("*.py")) + sorted((ROOT / "provings").glob("*.py"))


def _text_files() -> list[Path]:
    files = _python_files()
    readme = ROOT / "README"
    if readme.exists():
        files.append(readme)
    files += sorted((ROOT / "scripts").glob("*.sh"))
    return files


def test_no_inline_comments() -> None:
    for path in _python_files():
        with tokenize.open(path) as handle:
            for token in tokenize.generate_tokens(handle.readline):
                assert token.type != tokenize.COMMENT, f"{path}:{token.start}"


def test_no_docstrings() -> None:
    holders = (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
    for path in _python_files():
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            if isinstance(node, holders):
                assert ast.get_docstring(node) is None, str(path)


def test_no_forbidden_phrases() -> None:
    for path in _text_files():
        if path.resolve() == SELF:
            continue
        body = path.read_text().lower()
        for phrase in FORBIDDEN:
            assert phrase not in body, f"{path}:{phrase}"


def test_no_emoji() -> None:
    for path in _text_files():
        assert EMOJI.search(path.read_text()) is None, str(path)
